const skills = [
  { name: "JavaScript" },
  { name: "Python" },
  { name: "Adobe Photoshop" },
  { name: "Copywriting" },
  { name: "SEO" },
  { name: "Video Editing" },
  { name: "HTML" },
  { name: "CSS" },
  { name: "Java" },
  { name: "TypeScript" },
  { name: "React.js" },
  { name: "Vue.js" },
  { name: "Angular" },
  { name: "Node.js" },
  { name: "Express.js" },
  { name: "Python" },
  { name: "Django" },
  { name: "Flask" },
  { name: "Spring Boot" },
  { name: "C++" },
  { name: "C#" },
  { name: ".NET" },
  { name: "PHP" },
  { name: "Laravel" },
  { name: "Ruby on Rails" },
  { name: "Illustrator" },
  { name: "Figma" },
  { name: "Canva" },
  { name: "Blender" },
  { name: "InDesign" },
  { name: "GIMP" },
  { name: "CorelDRAW" },
  { name: "UI/UX Design" },
  { name: "3D Modeling" },
  { name: "Vector Design" },
  { name: "Motion Graphics" },
  { name: "Typography" },
  { name: "Logo Design" },
  { name: "Branding" },
  { name: "Infographic Design" },
  { name: "Content Writing" },
  { name: "Blog Writing" },
  { name: "SEO Writing" },
  { name: "Script Writing" },
  { name: "Copywriting" },
  { name: "Book Writing" },
  { name: "Dịch thuật Anh - Việt" },
  { name: "Dịch thuật Nhật - Việt" },
  { name: "Digital Marketing" },
  { name: "SEO Optimization" },
  { name: "Social Media Marketing" },
  { name: "Quảng cáo Facebook Ads" },
  { name: "Quảng cáo Google Ads" },
  { name: "Email Marketing" },
  { name: "Dropshipping" },
  { name: "Bán hàng trên Amazon" },
  { name: "Affiliate Marketing" },
  { name: "Quản lý dự án (Project Management)" },
  { name: "Nghiên cứu thị trường" },
  { name: "Music Composition" },
  { name: "Mixing & Mastering" },
  { name: "Music Production" },
  { name: "Voice Over" },
  { name: "Podcast" },
  { name: "Audio Editing" },
  { name: "Beatmaking" },
  { name: "Sound Design" },
  { name: "Lyric Writing" },
  { name: "Hòa âm phối khí" },
  { name: "Video Editing" },
  { name: "After Effects" },
  { name: "Premiere Pro" },
  { name: "Làm hoạt hình 2D" },
  { name: "Làm hoạt hình 3D" },
  { name: "Stop Motion" },
  { name: "Tạo Trailer" },
  { name: "Tạo hiệu ứng VFX" },
  { name: "Tạo intro/outro video" },
  { name: "Biên tập video TikTok, YouTube" },

  
]
module.exports = skills;